version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "new-redis-server"
    ports:
      - "6380:6379"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.pub
    command: uvicorn publisher:app --host 0.0.0.0 --port 8080
    container_name: "publisher-1"
    depends_on:
      - redis
    ports:
      - "8000:8000"

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.sub
    command: python subscriber.py
    container_name: "subscriber-1"
    depends_on:
      - redis
