FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./subscriber.py /app/subscriber.py

CMD ["python", "subscriber.py"]
